POST POST http://10.0.2.2/flutter/server.php HTTP/1.1
Content-Type: application/json

{
   
    "type": "maize",
    "x_coordinate": -122.222657,
    "y_coordinate": 0.2323223,
    "lat": lat,
    "long": long,
} 
