POST https://edwin-muhoro.ninja/public_html/server.php HTTP/1.1
Content-Type: application/json

{
   
    
    "x_coordinate": -122.222657,
    "y_coordinate": 0.2323223,
    "latitude": -122.222657,
    "longitude": 0.2323223,
    "type": "maize"
} 
